apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    type: infrastructure
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        env: 
        - name: SERVERURL
          value: "provisioner-service.default.svc.cluster.local:8080"
        - name: PORT
          value: "9000"
        image: talharegistry.azurecr.io/client:0.0.0
        resources:
          requests:
            memory: "50Mi"
            cpu: "50m"
          limits:
            memory: "100Mi"
            cpu: "100m"
        command: ["npm"]
        args: ["run","start"]
        ports:
        - containerPort: 9000
        imagePullPolicy: IfNotPresent
      imagePullSecrets:
      - name: talhasecret
      priorityClassName: high-priority
